import React from 'react'
import List from '../Components/List'
import Head from 'next/head'

const Home = () => {
  return (
    <>
      <Head>
          <title>Home Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link 
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,400;0,500;0,600;0,700;1,300&display=swap" 
            rel="stylesheet"
          />
      </Head>

      <div className="font-main w-full min-h-screen bg-[#DCDCFF] leading-5">
        {/* <div className="flex items-center p-4 bg-white shadow-md  ">
          <h1 className="font-semibold">My Kanban Board</h1>
        </div> */}
        <div className="flex flex-row flex-wrap justify-center pt-4 px-8  ">
          <List />
          <List />
          <List />
          <List />
        </div>
      </div>
    </>
  )
}

export default Home