import React, { useState, useEffect } from 'react'
import List from '../Components/List'
import Head from 'next/head'

const Home = () => {

  const [listData, setListData] = useState([])

  const fetchData = async () => {
    const res = await fetch('/api/list')
    const data = await res.json()
    console.log(res)
    setListData(data)
  }

  useEffect(() => {
    fetchData()
  }, [])

  return (
    <>
      <Head>
          <title>Home Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link 
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,400;0,500;0,600;0,700;1,300&display=swap"
          />
      </Head>

      <div className="font-main w-full min-h-screen bg-[#DCDCFF] leading-5">
        {/* <div className="flex items-center p-4 bg-white shadow-md  ">
          <h1 className="font-semibold">My Kanban Board</h1>
        </div> */}
        <div className="flex flex-row flex-wrap justify-center py-8 px-8">
          
          <List />



          {/* <List />
          <List />
          <List /> */}
        </div>
      </div>
    </>
  )
}

export default Home